use crate::models::{battle_class::BattleClass, card_asset::CardAsset};

pub const CARDS: &[CardAsset] = &[
    CardAsset {
        index: 1,
        name: "Goblin",
        attack: 0,
        battle_class: BattleClass::Physical,
        phys_defense: 0,
        mag_defense: 0,
    },
    CardAsset {
        index: 2,
        name: "Fang",
        attack: 0,
        battle_class: BattleClass::Physical,
        phys_defense: 0,
        mag_defense: 0,
    },
    CardAsset {
        index: 3,
        name: "Skeleton",
        attack: 0,
        battle_class: BattleClass::Physical,
        phys_defense: 0,
        mag_defense: 0,
    },
    CardAsset {
        index: 4,
        name: "Flan",
        attack: 0,
        battle_class: BattleClass::Magic,
        phys_defense: 0,
        mag_defense: 16,
    },
    CardAsset {
        index: 5,
        name: "Zaghnol",
        attack: 0,
        battle_class: BattleClass::Physical,
        phys_defense: 0,
        mag_defense: 0,
    },
    CardAsset {
        index: 6,
        name: "Lizard Man",
        attack: 0,
        battle_class: BattleClass::Physical,
        phys_defense: 0,
        mag_defense: 0,
    },
    CardAsset {
        index: 7,
        name: "Zombie",
        attack: 16,
        battle_class: BattleClass::Magic,
        phys_defense: 16,
        mag_defense: 0,
    },
    CardAsset {
        index: 8,
        name: "Bomb",
        attack: 1,
        battle_class: BattleClass::Magic,
        phys_defense: 0,
        mag_defense: 16,
    },
];
